version: 2

sources:
  - name: raw
    description: CSV files uploaded to source demo tables
    tables:
      - name: raw_items
      - name: raw_users
      - name: raw_purchases

models: 
  - name: customer
    description: This table has basic information about a customer, as well as some derived facts

    columns: 
      - name: user_id
        description: this is a unique identifier for a customer
        tests: 
          - unique
          - not_null
  
  - name: items_purchased
    description: new model to calculate most popular items
    columns: 
      - name: item_id
        description: unique identifier
        tests:
          - unique 
          - not_null